-- =============================================================================
-- SnowLens access probe (Snowflake Scripting)
-- =============================================================================
-- Run as the proposed service role.
-- Output: table SNOWLENS_ACCESS_PROBE_RESULTS with OK/FAIL per object.
--
-- Map FAIL rows using docs/16-kpi-source-access-matrix.md Part C.
-- Phase-1 blockers are listed in the final SELECT.
-- =============================================================================

CREATE OR REPLACE TEMPORARY TABLE SNOWLENS_ACCESS_PROBE_RESULTS (
  probed_at   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  tier_hint   VARCHAR,
  object_name VARCHAR,
  check_type  VARCHAR,
  status      VARCHAR,
  detail      VARCHAR
);

EXECUTE IMMEDIATE $$
DECLARE
  err VARCHAR;
BEGIN
  -- ---------- helpers via repeated try pattern ----------

  -- T1 METERING_HISTORY
  BEGIN
    DESCRIBE VIEW SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_HISTORY', 'VIEW', 'OK', 'visible');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT SERVICE_TYPE, CREDITS_USED, START_TIME
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_HISTORY', 'COLUMNS', 'OK', 'SERVICE_TYPE,CREDITS_USED,START_TIME');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT CREDITS_USED_CLOUD_SERVICES, CREDITS_ADJUSTMENT_CLOUD_SERVICES, USAGE_DATE
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_DAILY_HISTORY', 'COLUMNS', 'OK', 'cloud services adjustment');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.METERING_DAILY_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT WAREHOUSE_NAME, START_TIME, CREDITS_USED, CREDITS_USED_COMPUTE,
           CREDITS_ATTRIBUTED_COMPUTE_QUERIES
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY', 'COLUMNS', 'OK',
            'idle via CREDITS_ATTRIBUTED_COMPUTE_QUERIES');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT WAREHOUSE_NAME, START_TIME, AVG_RUNNING, AVG_QUEUED_LOAD,
           AVG_QUEUED_PROVISIONING, AVG_BLOCKED
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY', 'COLUMNS', 'OK', 'consolidation load');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT TIMESTAMP, WAREHOUSE_NAME, EVENT_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY', 'COLUMNS', 'OK', 'uptime events');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT QUERY_ID, QUERY_PARAMETERIZED_HASH, WAREHOUSE_NAME, WAREHOUSE_SIZE,
           START_TIME, END_TIME, TOTAL_ELAPSED_TIME, EXECUTION_STATUS, ROLE_NAME,
           BYTES_SCANNED, BYTES_WRITTEN_TO_RESULT,
           BYTES_SPILLED_TO_REMOTE_STORAGE, BYTES_SPILLED_TO_LOCAL_STORAGE,
           PARTITIONS_SCANNED, PARTITIONS_TOTAL,
           PERCENTAGE_SCANNED_FROM_CACHE, QUERY_TYPE, QUERY_RETRY_TIME
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_HISTORY', 'COLUMNS', 'OK', 'phase-1 slim columns');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT QUERY_PARAMETERIZED_HASH
    FROM SNOWFLAKE.ACCOUNT_USAGE.AGGREGATE_QUERY_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.AGGREGATE_QUERY_HISTORY', 'COLUMNS', 'OK', 'shape aggregates');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.AGGREGATE_QUERY_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT QUERY_ID, QUERY_PARAMETERIZED_HASH, CREDITS_ATTRIBUTED_COMPUTE,
           USER_NAME, ROLE_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY', 'COLUMNS', 'OK', 'attribution');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT QUERY_ID FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_METERING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_METERING_HISTORY', 'VIEW', 'OK', 'adaptive substitute');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_METERING_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT QUERY_ID, INSIGHT_TYPE_ID, IS_OPPORTUNITY
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_INSIGHTS WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_INSIGHTS', 'COLUMNS', 'OK', 'native insights');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_INSIGHTS', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT TABLE_ID, CREDITS_USED
    FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY', 'COLUMNS', 'OK', 'AC credits');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_DML_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_DML_HISTORY', 'VIEW', 'OK', 'DML history');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_DML_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_PRUNING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_PRUNING_HISTORY', 'VIEW', 'OK', 'table pruning');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_PRUNING_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMN_QUERY_PRUNING_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.COLUMN_QUERY_PRUNING_HISTORY', 'VIEW', 'OK', 'column pruning');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.COLUMN_QUERY_PRUNING_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SEARCH_OPTIMIZATION_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.SEARCH_OPTIMIZATION_HISTORY', 'VIEW', 'OK', 'SO cost');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.SEARCH_OPTIMIZATION_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.SEARCH_OPTIMIZATION_BENEFITS WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.SEARCH_OPTIMIZATION_BENEFITS', 'VIEW', 'OK', 'SO benefits');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.SEARCH_OPTIMIZATION_BENEFITS', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ACCELERATION_HISTORY', 'VIEW', 'OK', 'QAS cost');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ACCELERATION_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE', 'VIEW', 'OK', 'QAS eligible');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY', 'VIEW', 'OK', 'MV refresh');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT TABLE_NAME, ACTIVE_BYTES, TIME_TRAVEL_BYTES, FAILSAFE_BYTES, RETAINED_FOR_CLONE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_STORAGE_METRICS', 'COLUMNS', 'OK', 'storage metrics');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1', 'ACCOUNT_USAGE.TABLE_STORAGE_METRICS', 'COLUMNS', 'FAIL', :err);
  END;

  -- T2
  BEGIN
    SELECT TABLE_ID, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, BYTES, RETENTION_TIME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.TABLES', 'COLUMNS', 'OK', 'tables');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.TABLES', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT TABLE_ID, COLUMN_NAME, DATA_TYPE
    FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.COLUMNS', 'COLUMNS', 'OK', 'columns');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.COLUMNS', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.OBJECT_DEPENDENCIES', 'VIEW', 'OK', 'dependencies');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.OBJECT_DEPENDENCIES', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.TAG_REFERENCES', 'VIEW', 'OK', 'tags');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T2', 'ACCOUNT_USAGE.TAG_REFERENCES', 'VIEW', 'FAIL', :err);
  END;

  -- T3
  BEGIN
    SELECT QUERY_ID, QUERY_START_TIME, USER_NAME,
           BASE_OBJECTS_ACCESSED, DIRECT_OBJECTS_ACCESSED, OBJECTS_MODIFIED
    FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T3', 'ACCOUNT_USAGE.ACCESS_HISTORY', 'COLUMNS', 'OK', 'governance access history');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T3', 'ACCOUNT_USAGE.ACCESS_HISTORY', 'COLUMNS', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.AGGREGATE_ACCESS_HISTORY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T3', 'ACCOUNT_USAGE.AGGREGATE_ACCESS_HISTORY', 'VIEW', 'OK', 'aggregate access');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T3', 'ACCOUNT_USAGE.AGGREGATE_ACCESS_HISTORY', 'VIEW', 'FAIL', :err);
  END;

  -- T4 (expected FAIL outside org account)
  BEGIN
    SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T4', 'ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY', 'VIEW', 'OK', 'currency');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T4', 'ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY', 'VIEW', 'FAIL', :err);
  END;

  BEGIN
    SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.RATE_SHEET_DAILY WHERE 1=0;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T4', 'ORGANIZATION_USAGE.RATE_SHEET_DAILY', 'VIEW', 'OK', 'rates');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T4', 'ORGANIZATION_USAGE.RATE_SHEET_DAILY', 'VIEW', 'FAIL', :err);
  END;

  -- SHOW WAREHOUSES
  BEGIN
    SHOW WAREHOUSES;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1*', 'SHOW WAREHOUSES', 'SHOW', 'OK', 'config snapshot possible');
  EXCEPTION WHEN OTHER THEN
    err := SQLERRM;
    INSERT INTO SNOWLENS_ACCESS_PROBE_RESULTS (tier_hint, object_name, check_type, status, detail)
    VALUES ('T1*', 'SHOW WAREHOUSES', 'SHOW', 'FAIL', :err);
  END;

END;
$$;

-- Full report
SELECT tier_hint, object_name, check_type, status, detail, probed_at
FROM SNOWLENS_ACCESS_PROBE_RESULTS
ORDER BY
  CASE tier_hint
    WHEN 'T1' THEN 1 WHEN 'T1*' THEN 2 WHEN 'T2' THEN 3
    WHEN 'T3' THEN 4 WHEN 'T4' THEN 5 ELSE 6
  END,
  object_name,
  check_type;

-- Counts by tier
SELECT
  tier_hint,
  COUNT_IF(status = 'OK')   AS ok_count,
  COUNT_IF(status = 'FAIL') AS fail_count
FROM SNOWLENS_ACCESS_PROBE_RESULTS
GROUP BY 1
ORDER BY 1;

-- Phase-1 hard blockers (idle + consolidation)
SELECT object_name, status, detail
FROM SNOWLENS_ACCESS_PROBE_RESULTS
WHERE object_name IN (
  'ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY',
  'ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY',
  'ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY',
  'ACCOUNT_USAGE.QUERY_HISTORY',
  'SHOW WAREHOUSES'
)
ORDER BY object_name;
